### ISSUE TITLE
Beta fixes from Jon

### ISSUE THREAD

**Issue by jonfriskics** [pluralsight-projects/Vue-BookListing-Forms#1]
- [x] update README - needs to have some changes that make the README specific to this project and not the Build a Reading List Application project that it was built on top of.

**Comment by jonfriskics** [comment]
- [ ] Set version to 2.x instead of 2.5.16

**Comment by jonfriskics** [comment]
- [ ] what do you think about the title being `Add Features with Forms to a Vue.js Reading List Application`?

**Comment by jonfriskics** [comment]
- [ ] what do you think about changing the module titled `Dynamically Show and Hide Text with v-if and v-else` to `Dynamically Show and Hide Text`?

**Comment by jonfriskics** [comment]
- [ ] change the module test commands in package.json (and in content tools for each module) to `1-4` instead of `2-5` like they are right now.

**Comment by jonfriskics** [comment]
Set the durations for each module.  I recommend:

Setup: 15min
Module 1: 20min
Module 2: 15min
Module 3: 30min
Module 4: 15min

**Comment by carolinapowers** [comment]
>  change the module test commands in package.json (and in content tools for each module) to 1-4 instead of 2-5 like they are right now.

I find it pretty confusing to the user to be running `test:module1` in module 2, when the UI shows them that module 1 is the setup module. Don't you agree?

**Comment by carolinapowers** [comment]
> Add Features with Forms to a Vue.js Reading List Application

Chose the first option.
